### ISSUE TITLE
Not working with Inifinite Scroller Adapter.  

### ISSUE THREAD

**Issue by shriharsha-bhagwat** [r-cohen/DiscreteScrollViewIndicator#1]
1. Not working with Inifinite Scroller Adapter: App freezes.
2. Some extra lines come up when i use this paging indicator.

**Comment by droid-lover** [comment]
any updates ??

**Comment by raphael-anydo** [comment]
it can probably get worked around: this decorator uses the adapter to check the number of items `int itemCount = parent.getAdapter().getItemCount();`, maybe the adapter you are using returns a wrong value for items count? actually InfinitScrollAdapter sets the count to `Integer.MAX_VALUE` which explains why it doesn't work. an easy fix is to add a setter for items count.

**Comment by r-cohen** [comment]
has been fixed by setting items count. see latest [README](https://github.com/r-cohen/DiscreteScrollViewIndicator/blob/master/README.md) for more info.
