### ISSUE TITLE
Doesnt work with InfinitePageAdapter

### ISSUE THREAD

**Issue by droid-lover** [r-cohen/DiscreteScrollViewIndicator#2]
Doesnt work with InfinitePageAdapter

**Comment by raphael-anydo** [comment]
InfinitePagerAdapter returns `Integer.MAX_VALUE` when calling `getCount`. this view indicator needs the number of items, this is why it doesn't work. a workaround can be to add a setter for the number of items in the indicator.

**Comment by r-cohen** [comment]
has been fixed by setting items count. see latest [README](https://github.com/r-cohen/DiscreteScrollViewIndicator/blob/master/README.md) for more info.
